In [1]:
import numpy as np

In [2]:
import sklearn

In [3]:
Array = np.array([3,5,6,7])

In [4]:
Array


array([3, 5, 6, 7])

In [5]:
Array.dtype


dtype('int32')

# conversion array creation

In [7]:
list = np.array([[7,56,6], [6,5,84], [89,565,45]])

In [8]:
list


array([[  7,  56,   6],
       [  6,   5,  84],
       [ 89, 565,  45]])

In [11]:
rng = np.arange(15)

In [12]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
lspace = np.linspace(1,5,6)

In [15]:
lspace


array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [17]:
emp = np.empty((4,4))


In [18]:
emp


array([[6.23042070e-307, 7.56587584e-307, 1.11258854e-306,
        1.11261502e-306],
       [1.42410839e-306, 7.56597770e-307, 6.23059726e-307,
        1.42418987e-306],
       [1.33511562e-306, 1.42420209e-306, 1.78019082e-306,
        9.79097007e-307],
       [7.56601165e-307, 1.11260144e-306, 8.34448533e-308,
        1.42404727e-306]])

In [20]:
i = np.identity(4)

In [21]:
i


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
i.ravel()


array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [24]:
x = [[1,2,3], [4,5,6], [7,8,9]]


In [25]:
ar = np.array(x)

In [26]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [27]:
ar.T


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [31]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [32]:
ar.argmax()

8

In [33]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [34]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [37]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [38]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [39]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [41]:
ar2 = np.array([[1,4,5], [8,9,7],[6,5,6]])

## 

In [42]:
ar*ar2

array([[ 1,  8, 15],
       [32, 45, 42],
       [42, 40, 54]])

In [43]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [44]:
import sys

In [45]:
ch_ar = [1,5,6,7]


In [46]:
np_ar = np.array(ch_ar)

In [48]:
sys.getsizeof(1)*len(ch_ar)

112

In [49]:
np_ar.itemsize*np_ar.size

16

In [50]:
np_ar.tolist()

[1, 5, 6, 7]